# Generated by Django 5.0.4 on 2024-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normal', models.CharField(max_length=5)),
                ('fire', models.CharField(max_length=5)),
                ('water', models.CharField(max_length=5)),
                ('electric', models.CharField(max_length=5)),
                ('grass', models.CharField(max_length=5)),
                ('ice', models.CharField(max_length=5)),
                ('fighting', models.CharField(max_length=5)),
                ('poison', models.CharField(max_length=5)),
                ('ground', models.CharField(max_length=5)),
                ('flying', models.CharField(max_length=5)),
                ('psychic', models.CharField(max_length=5)),
                ('bug', models.CharField(max_length=5)),
                ('rock', models.CharField(max_length=5)),
                ('ghost', models.CharField(max_length=5)),
                ('dragon', models.CharField(max_length=5)),
                ('dark', models.CharField(max_length=5)),
                ('steel', models.CharField(max_length=5)),
                ('fairy', models.CharField(max_length=5)),
            ],
        ),
    ]
